import type {
  Health,
  Heatmap,
  LiveStats,
  MentionDetail,
  MentionList,
  Mention,
  PriorityRow,
  QueueList,
} from './types';

export const MOCK_HEALTH: Health = {
  ok: true,
  operator: 'MTN Nigeria',
  operator_handle: 'MTNNigeria',
  apify_configured: false,
  anthropic_configured: false,
};

export const MOCK_LIVE_STATS: LiveStats = {
  total_mentions_24h: 847,
  auto_resolved_24h: 531,
  escalated_24h: 114,
  avg_response_seconds: 167,
  auto_resolve_rate: 0.627,
  by_category: [
    { category: 'Data Depletion', count: 218 },
    { category: 'Network / Connectivity', count: 187 },
    { category: 'Billing & Charges', count: 142 },
    { category: 'Customer Service Complaint', count: 118 },
    { category: 'Recharge & Vouchers', count: 89 },
    { category: 'SIM & Account Issues', count: 54 },
    { category: 'Service Activation', count: 39 },
  ],
  by_pathway: [
    { pathway: 'AUTO_REPLY', count: 531 },
    { pathway: 'AGENT_PING', count: 202 },
    { pathway: 'ESCALATE_FLAG', count: 114 },
  ],
  timeseries: [
    { hour: '00:00', count: 14 }, { hour: '01:00', count: 9 },
    { hour: '02:00', count: 6 },  { hour: '03:00', count: 4 },
    { hour: '04:00', count: 5 },  { hour: '05:00', count: 11 },
    { hour: '06:00', count: 28 }, { hour: '07:00', count: 47 },
    { hour: '08:00', count: 62 }, { hour: '09:00', count: 71 },
    { hour: '10:00', count: 68 }, { hour: '11:00', count: 74 },
    { hour: '12:00', count: 82 }, { hour: '13:00', count: 79 },
    { hour: '14:00', count: 76 }, { hour: '15:00', count: 83 },
    { hour: '16:00', count: 91 }, { hour: '17:00', count: 88 },
    { hour: '18:00', count: 77 }, { hour: '19:00', count: 64 },
    { hour: '20:00', count: 52 }, { hour: '21:00', count: 41 },
    { hour: '22:00', count: 33 }, { hour: '23:00', count: 22 },
  ],
  top_risk: [
    { handle: 'emeka_abuja', display_name: 'Emeka Okafor', region: 'Abuja', arpu_naira: 38500, risk: 97 },
    { handle: 'chinwe_ph', display_name: 'Chinwe Eze', region: 'Port Harcourt', arpu_naira: 44200, risk: 94 },
    { handle: 'bayo_lagos1', display_name: 'Bayo Adeyemi', region: 'Lagos', arpu_naira: 51200, risk: 91 },
    { handle: 'kola_ade_business', display_name: 'Kolawole Adebayo', region: 'Lagos', arpu_naira: 62000, risk: 89 },
    { handle: 'ngozi_enugu', display_name: 'Ngozi Nwosu', region: 'Enugu', arpu_naira: 24750, risk: 87 },
    { handle: 'ifeanyi_owerri', display_name: 'Ifeanyi Obi', region: 'Owerri', arpu_naira: 19800, risk: 84 },
    { handle: 'hassan_kano', display_name: 'Hassan Musa', region: 'Kano', arpu_naira: 16400, risk: 81 },
    { handle: 'tunde_ibadan', display_name: 'Tunde Fashola', region: 'Ibadan', arpu_naira: 29800, risk: 79 },
  ],
};

export const MOCK_MENTIONS: Mention[] = [
  // --- CRITICAL escalations (escalated to queue) ---
  {
    id: 1,
    tweet_id: '1780001000001',
    text: "@MTNNigeria why has my 10GB data bundle finished in 2 days? I bought it last Friday and I've barely used my phone. This is highway robbery! #MTNNigeria #DataTheft",
    posted_at: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    likes: 47, retweets: 22, replies: 14,
    url: 'https://twitter.com/emeka_abuja/status/1780001000001',
    customer: {
      id: 101, handle: 'emeka_abuja', display_name: 'Emeka Okafor',
      msisdn: '08031234567', region: 'Abuja', tenure_months: 38,
      arpu_naira: 38500, verified: false, followers: 4240,
    },
    classification: {
      category: 'Data Depletion', urgency: 9, pathway: 'ESCALATE_FLAG',
      sentiment: 'negative', language: 'en', confidence: 0.96,
      churn_risk: 0.97, risk_level: 'CRITICAL',
      risk_factors: ['High ARPU subscriber', 'Third complaint this month', 'Public tweet with high engagement'],
      ai_summary: 'High-value Abuja subscriber reporting premature 10GB bundle depletion. Pattern of repeated complaints. High public visibility.',
      ai_reply: "Hi Emeka, we're very sorry about your data experience. We've flagged your account for urgent review and will reach out within 2 hours with a full resolution. ^ORCA",
      suggested_offer: 'Free 5GB data bonus + account audit + priority callback',
    },
    escalation: {
      id: 1001, status: 'QUEUED', assigned_to: '',
      queued_at: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
      accepted_at: null, resolved_at: null, notes: '', final_reply: '',
    },
  },
  {
    id: 2,
    tweet_id: '1780001000002',
    text: "@MTNNigeria network has been completely down in Lekki Phase 1 since yesterday evening. I work from home — I've lost an entire day of productivity and missed 3 client calls. What is going on??",
    posted_at: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    likes: 131, retweets: 78, replies: 41,
    url: 'https://twitter.com/bayo_lagos1/status/1780001000002',
    customer: {
      id: 102, handle: 'bayo_lagos1', display_name: 'Bayo Adeyemi',
      msisdn: '08057891234', region: 'Lagos', tenure_months: 54,
      arpu_naira: 51200, verified: true, followers: 28900,
    },
    classification: {
      category: 'Network / Connectivity', urgency: 10, pathway: 'ESCALATE_FLAG',
      sentiment: 'negative', language: 'en', confidence: 0.98,
      churn_risk: 0.91, risk_level: 'CRITICAL',
      risk_factors: ['Verified account', 'High follower count', 'Business-impacting outage', 'Lekki coverage gap confirmed'],
      ai_summary: 'Verified high-ARPU Lagos subscriber reporting extended network outage in Lekki Phase 1. Business impact with high public reach.',
      ai_reply: "Hi Bayo, we sincerely apologise for the disruption. Our engineers are aware of the Lekki area issue and are working to restore full service. ETA: 3 hours. We'll keep you updated. ^ORCA",
      suggested_offer: '2-day service credit + priority callback from Area Manager',
    },
    escalation: {
      id: 1002, status: 'ACCEPTED', assigned_to: 'agent_sarah',
      queued_at: new Date(Date.now() - 85 * 60 * 1000).toISOString(),
      accepted_at: new Date(Date.now() - 75 * 60 * 1000).toISOString(),
      resolved_at: null,
      notes: 'Lekki Phase 1 outage confirmed by NOC. Tower maintenance overran. Coordinating with network team for ETA.',
      final_reply: '',
    },
  },
  {
    id: 3,
    tweet_id: '1780001000003',
    text: "@MTNNigeria I was charged ₦8,500 twice for my monthly plan renewal. Duplicate deduction on the same day. Three days now and no reversal. I want my money back NOW or I'm porting to Airtel.",
    posted_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    likes: 28, retweets: 11, replies: 6,
    url: 'https://twitter.com/chinwe_ph/status/1780001000003',
    customer: {
      id: 103, handle: 'chinwe_ph', display_name: 'Chinwe Eze',
      msisdn: '08098765432', region: 'Port Harcourt', tenure_months: 71,
      arpu_naira: 44200, verified: false, followers: 2840,
    },
    classification: {
      category: 'Billing & Charges', urgency: 9, pathway: 'ESCALATE_FLAG',
      sentiment: 'negative', language: 'en', confidence: 0.97,
      churn_risk: 0.94, risk_level: 'CRITICAL',
      risk_factors: ['Explicit porting threat', 'Duplicate billing confirmed', 'Long-tenured subscriber', 'Financial harm'],
      ai_summary: 'Long-tenured Port Harcourt subscriber with explicit porting threat due to unresolved ₦8,500 duplicate charge. Immediate action needed.',
      ai_reply: "Hi Chinwe, we're very sorry for this billing error. We've initiated an immediate reversal of the duplicate charge. You'll see the credit within 24 hours. We're also sending a goodwill gesture for the delay. ^ORCA",
      suggested_offer: 'Immediate ₦8,500 reversal + ₦3,000 goodwill credit + personal apology call',
    },
    escalation: {
      id: 1003, status: 'QUEUED', assigned_to: '',
      queued_at: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
      accepted_at: null, resolved_at: null, notes: '', final_reply: '',
    },
  },
  {
    id: 4,
    tweet_id: '1780001000004',
    text: "@MTNNigeria been a loyal customer for 8 years. Spent over ₦500k in recharges. Your new data pricing is completely unacceptable — 1GB for ₦1,500? Absolutely disgraceful. Posting this thread so everyone knows. [1/5]",
    posted_at: new Date(Date.now() - 4.5 * 60 * 60 * 1000).toISOString(),
    likes: 512, retweets: 347, replies: 218,
    url: 'https://twitter.com/kola_ade_business/status/1780001000004',
    customer: {
      id: 104, handle: 'kola_ade_business', display_name: 'Kolawole Adebayo',
      msisdn: '08022334455', region: 'Lagos', tenure_months: 96,
      arpu_naira: 62000, verified: true, followers: 47200,
    },
    classification: {
      category: 'Billing & Charges', urgency: 10, pathway: 'ESCALATE_FLAG',
      sentiment: 'negative', language: 'en', confidence: 0.99,
      churn_risk: 0.89, risk_level: 'CRITICAL',
      risk_factors: ['Viral thread — 500+ engagements', 'Verified account, 47k followers', 'Top-tier ARPU', '8-year subscriber'],
      ai_summary: 'Very high-value 8-year subscriber starting a viral complaint thread about data pricing. Extremely high reputational risk.',
      ai_reply: "Hi Kola, your loyalty means everything to us. A senior member of our team will reach out to you directly within the hour to discuss your concerns and make things right. ^ORCA",
      suggested_offer: 'VIP account review + exclusive loyalty data bundle + direct line to senior CX manager',
    },
    escalation: {
      id: 1004, status: 'ACCEPTED', assigned_to: 'agent_michael',
      queued_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      accepted_at: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString(),
      resolved_at: null,
      notes: 'Viral thread, escalated to CX Director. Monitoring for further spread. Preparing personal outreach.',
      final_reply: '',
    },
  },
  {
    id: 5,
    tweet_id: '1780001000005',
    text: "@MTNNigeria SIM swap done without my knowledge! My line has been hijacked and my bank keeps sending OTPs to another device. I've lost access to my UBA account. This is a SECURITY EMERGENCY.",
    posted_at: new Date(Date.now() - 1.2 * 60 * 60 * 1000).toISOString(),
    likes: 89, retweets: 54, replies: 31,
    url: 'https://twitter.com/ngozi_enugu/status/1780001000005',
    customer: {
      id: 105, handle: 'ngozi_enugu', display_name: 'Ngozi Nwosu',
      msisdn: '08044445555', region: 'Enugu', tenure_months: 45,
      arpu_naira: 24750, verified: false, followers: 1920,
    },
    classification: {
      category: 'Fraud & Security', urgency: 10, pathway: 'ESCALATE_FLAG',
      sentiment: 'negative', language: 'en', confidence: 0.99,
      churn_risk: 0.87, risk_level: 'CRITICAL',
      risk_factors: ['Active SIM swap fraud', 'Bank account compromise', 'Legal liability risk', 'Active financial loss ongoing'],
      ai_summary: 'Subscriber reporting active SIM swap fraud with live bank account compromise. Immediate SIM block and fraud team escalation required.',
      ai_reply: "Ngozi, this is extremely urgent — we're locking your SIM RIGHT NOW and escalating to our fraud team. Please call 180 immediately for emergency assistance. ^ORCA",
      suggested_offer: 'Immediate SIM block + fraud team callback within 15 min + full incident report',
    },
    escalation: {
      id: 1005, status: 'ACCEPTED', assigned_to: 'fraud_team_lead',
      queued_at: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
      accepted_at: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
      resolved_at: null,
      notes: 'SIM swap confirmed. Fraud team engaged. Coordinating with UBA security. SIM suspended pending investigation.',
      final_reply: '',
    },
  },
  {
    id: 6,
    tweet_id: '1780001000006',
    text: "@MTNNigeria your customer care line kept me on hold for 2 hours and 17 minutes. The agent then hung up without resolving anything. I am a business customer paying ₦45,000/month. Is this how you treat your subscribers?",
    posted_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    likes: 74, retweets: 39, replies: 22,
    url: 'https://twitter.com/ifeanyi_owerri/status/1780001000006',
    customer: {
      id: 106, handle: 'ifeanyi_owerri', display_name: 'Ifeanyi Obi',
      msisdn: '08011223344', region: 'Owerri', tenure_months: 62,
      arpu_naira: 45000, verified: false, followers: 3100,
    },
    classification: {
      category: 'Customer Service Complaint', urgency: 8, pathway: 'ESCALATE_FLAG',
      sentiment: 'negative', language: 'en', confidence: 0.95,
      churn_risk: 0.84, risk_level: 'CRITICAL',
      risk_factors: ['Business-tier subscriber', '2h+ hold time', 'Agent hung up', 'Unresolved underlying issue'],
      ai_summary: 'Business-tier Owerri subscriber reporting 2+ hour hold time followed by agent disconnection. Unresolved issue still outstanding.',
      ai_reply: "Hi Ifeanyi, that experience is completely unacceptable and we take full responsibility. A dedicated senior agent will call you back within 30 minutes to resolve your issue completely. ^ORCA",
      suggested_offer: 'Priority callback within 30 min + 1 month service credit + formal apology',
    },
    escalation: {
      id: 1006, status: 'QUEUED', assigned_to: '',
      queued_at: new Date(Date.now() - 4.5 * 60 * 60 * 1000).toISOString(),
      accepted_at: null, resolved_at: null, notes: '', final_reply: '',
    },
  },
  {
    id: 7,
    tweet_id: '1780001000007',
    text: "@MTNNigeria new SIM registered 5 days ago and it STILL hasn't been activated. I've visited 3 different MTN offices. Every time they say 'try again tomorrow'. I have a business to run!",
    posted_at: new Date(Date.now() - 6.5 * 60 * 60 * 1000).toISOString(),
    likes: 34, retweets: 17, replies: 9,
    url: 'https://twitter.com/hassan_kano/status/1780001000007',
    customer: {
      id: 107, handle: 'hassan_kano', display_name: 'Hassan Musa',
      msisdn: '08066778899', region: 'Kano', tenure_months: 0,
      arpu_naira: 16400, verified: false, followers: 870,
    },
    classification: {
      category: 'Service Activation', urgency: 8, pathway: 'ESCALATE_FLAG',
      sentiment: 'negative', language: 'en', confidence: 0.93,
      churn_risk: 0.81, risk_level: 'HIGH',
      risk_factors: ['5-day activation failure', 'Multiple store visits', 'New subscriber at risk of immediate churn', 'Business impact'],
      ai_summary: 'New Kano subscriber with 5-day activation failure despite multiple store visits. High risk of immediate churn before relationship established.',
      ai_reply: "Hi Hassan, a 5-day activation delay is completely unacceptable. We're escalating directly to our technical provisioning team and will have your line active within 4 hours. ^ORCA",
      suggested_offer: 'Immediate provisioning escalation + 3GB welcome bonus + 1 month free plan',
    },
    escalation: {
      id: 1007, status: 'QUEUED', assigned_to: '',
      queued_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      accepted_at: null, resolved_at: null, notes: '', final_reply: '',
    },
  },
  {
    id: 8,
    tweet_id: '1780001000008',
    text: "@MTNNigeria ported from Glo 4 months ago and I regret every single day. Network drops 20+ times a day in Wuse II. My entire team is complaining. We're moving 14 lines back to Glo if this isn't fixed this week.",
    posted_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    likes: 156, retweets: 94, replies: 47,
    url: 'https://twitter.com/tunde_ibadan/status/1780001000008',
    customer: {
      id: 108, handle: 'tunde_ibadan', display_name: 'Tunde Fashola',
      msisdn: '08077889900', region: 'Abuja', tenure_months: 4,
      arpu_naira: 29800, verified: false, followers: 6800,
    },
    classification: {
      category: 'Network / Connectivity', urgency: 9, pathway: 'ESCALATE_FLAG',
      sentiment: 'negative', language: 'en', confidence: 0.97,
      churn_risk: 0.93, risk_level: 'CRITICAL',
      risk_factors: ['14-line corporate account at risk', 'Explicit 1-week ultimatum', 'Repeated daily drops confirmed', 'High revenue at stake'],
      ai_summary: 'Corporate account threatening to port 14 lines due to persistent Wuse II network drops. Deadline given. Extremely high revenue at risk.',
      ai_reply: "Hi Tunde, we're treating this as a corporate priority. Our Abuja Area Manager will call you within 2 hours to personally arrange a site inspection and resolution plan. ^ORCA",
      suggested_offer: 'Dedicated corporate account manager + 48h network SLA + service credit on all 14 lines',
    },
    escalation: {
      id: 1008, status: 'ACCEPTED', assigned_to: 'agent_corporate_abuja',
      queued_at: new Date(Date.now() - 7.5 * 60 * 60 * 1000).toISOString(),
      accepted_at: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
      resolved_at: null,
      notes: 'Corporate account — 14 lines. Wuse II network confirmed degraded. Escalated to Abuja Area Manager. Site inspection scheduled for tomorrow.',
      final_reply: '',
    },
  },
  // --- HIGH — agent ping ---
  {
    id: 9,
    tweet_id: '1780001000009',
    text: "@MTNNigeria your customer care line has kept me on hold for 45 minutes. This is unacceptable! Why can't you resolve simple issues online?",
    posted_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    likes: 8, retweets: 3, replies: 2,
    url: 'https://twitter.com/adaeze_obi/status/1780001000009',
    customer: {
      id: 109, handle: 'adaeze_obi', display_name: 'Adaeze Obiora',
      msisdn: '08011112222', region: 'Ibadan', tenure_months: 29,
      arpu_naira: 9800, verified: false, followers: 680,
    },
    classification: {
      category: 'Customer Service Complaint', urgency: 6, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.92,
      churn_risk: 0.61, risk_level: 'HIGH',
      risk_factors: ['Long hold time', 'Public frustration', 'Service quality concern'],
      ai_summary: 'Ibadan subscriber frustrated by 45-minute hold time. Mid-range ARPU, moderate churn risk.',
      ai_reply: "Hi Adaeze, we're very sorry for the wait — that's not the experience we want you to have. A dedicated agent will DM you right now to resolve your issue. ^ORCA",
      suggested_offer: 'Priority callback + ₦1,000 airtime credit',
    },
    escalation: null,
  },
  {
    id: 10,
    tweet_id: '1780001000010',
    text: "@MTNNigeria recharge voucher not working AGAIN. I bought ₦2,000 voucher card but it says invalid PIN. Third time this week! Are your retailers selling used cards??",
    posted_at: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    likes: 12, retweets: 6, replies: 3,
    url: 'https://twitter.com/funmi_abeokuta/status/1780001000010',
    customer: {
      id: 110, handle: 'funmi_abeokuta', display_name: 'Funmilayo Oke',
      msisdn: '08044445555', region: 'Abeokuta', tenure_months: 45,
      arpu_naira: 14750, verified: false, followers: 490,
    },
    classification: {
      category: 'Recharge & Vouchers', urgency: 7, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.91,
      churn_risk: 0.71, risk_level: 'HIGH',
      risk_factors: ['Repeated voucher failure', 'Possible retailer fraud', 'Financial loss'],
      ai_summary: 'Abeokuta subscriber reporting third invalid voucher PIN this week. Possible retailer-level fraud.',
      ai_reply: "Hi Funmilayo, we're sorry about this. Please DM us the PIN series so we can verify and credit your account immediately. We'll also flag the retailer for investigation. ^ORCA",
      suggested_offer: 'Full ₦2,000 credit + fraud investigation',
    },
    escalation: null,
  },
  {
    id: 11,
    tweet_id: '1780001000011',
    text: "@MTNNigeria my SmartConnect plan was supposed to auto-renew yesterday. Still showing expired. ₦15k sitting in my account not being deducted. Very frustrating.",
    posted_at: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    likes: 4, retweets: 1, replies: 0,
    url: 'https://twitter.com/obiora_ph/status/1780001000011',
    customer: {
      id: 111, handle: 'obiora_ph', display_name: 'Obiora Nwachukwu',
      msisdn: '08033445566', region: 'Port Harcourt', tenure_months: 33,
      arpu_naira: 15000, verified: false, followers: 340,
    },
    classification: {
      category: 'Service Activation', urgency: 6, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.89,
      churn_risk: 0.58, risk_level: 'HIGH',
      risk_factors: ['Auto-renewal failure', 'Service interruption', 'Billing system anomaly'],
      ai_summary: 'Port Harcourt subscriber with auto-renewal failure. Balance available but plan not renewing. Billing system investigation needed.',
      ai_reply: "Hi Obiora, we can see the renewal issue on our end. We've triggered a manual renewal for your SmartConnect plan — it should activate within 30 minutes. ^ORCA",
      suggested_offer: 'Manual renewal trigger + 1GB bonus for inconvenience',
    },
    escalation: null,
  },
  {
    id: 12,
    tweet_id: '1780001000012',
    text: "@MTNNigeria internet is extremely slow in Surulere since last night. Running speed tests showing 0.3 Mbps download. This is unusable. I pay for 4G service!",
    posted_at: new Date(Date.now() - 8.5 * 60 * 60 * 1000).toISOString(),
    likes: 19, retweets: 8, replies: 5,
    url: 'https://twitter.com/sade_surulere/status/1780001000012',
    customer: {
      id: 112, handle: 'sade_surulere', display_name: 'Sade Akinwale',
      msisdn: '08055667788', region: 'Lagos', tenure_months: 52,
      arpu_naira: 18500, verified: false, followers: 1240,
    },
    classification: {
      category: 'Network / Connectivity', urgency: 7, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.94,
      churn_risk: 0.68, risk_level: 'HIGH',
      risk_factors: ['Surulere area degradation', '4G throttling suspected', 'Overnight outage', 'Speed test evidence'],
      ai_summary: 'Lagos subscriber providing speed test evidence of severe 4G degradation in Surulere. Overnight issue.',
      ai_reply: "Hi Sade, we can see area-level congestion in Surulere right now. Our engineers are actively working on it. In the meantime, try toggling airplane mode — this can help reconnect to a stronger tower. ^ORCA",
      suggested_offer: '1GB data compensation + NOC escalation for Surulere tower',
    },
    escalation: null,
  },
  {
    id: 13,
    tweet_id: '1780001000013',
    text: "@MTNNigeria I've been trying to port to another network but the process keeps failing. Every time I dial *XXXX# it says 'request failed'. I have the right to port if I choose!",
    posted_at: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
    likes: 22, retweets: 14, replies: 8,
    url: 'https://twitter.com/chidi_onitsha/status/1780001000013',
    customer: {
      id: 113, handle: 'chidi_onitsha', display_name: 'Chidi Ozoemena',
      msisdn: '08088990011', region: 'Onitsha', tenure_months: 18,
      arpu_naira: 7600, verified: false, followers: 560,
    },
    classification: {
      category: 'SIM & Account Issues', urgency: 7, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.90,
      churn_risk: 0.77, risk_level: 'HIGH',
      risk_factors: ['Active porting attempt', 'NCC regulatory obligation', 'Technical blocking possible'],
      ai_summary: 'Onitsha subscriber attempting to port out. Porting process failing — needs resolution to comply with NCC regulations.',
      ai_reply: "Hi Chidi, we want to ensure your porting request is handled correctly and promptly. A specialist will contact you within 2 hours to assist with the process. ^ORCA",
      suggested_offer: 'Porting assistance + win-back offer: 3 months discounted premium plan',
    },
    escalation: null,
  },
  {
    id: 14,
    tweet_id: '1780001000014',
    text: "@MTNNigeria charged ₦500 airtime for 'caller tune service' I never subscribed to. This has been happening every 30 days for the last 4 months. I want all ₦2,000 back. Please stop these fraudulent deductions!",
    posted_at: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    likes: 37, retweets: 21, replies: 12,
    url: 'https://twitter.com/yetunde_lagos/status/1780001000014',
    customer: {
      id: 114, handle: 'yetunde_lagos', display_name: 'Yetunde Coker',
      msisdn: '08099001122', region: 'Lagos', tenure_months: 84,
      arpu_naira: 11200, verified: false, followers: 2100,
    },
    classification: {
      category: 'Billing & Charges', urgency: 7, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.95,
      churn_risk: 0.73, risk_level: 'HIGH',
      risk_factors: ['4-month unauthorized subscription', 'Pattern of VAS fraud', 'Reputational risk', 'Regulatory exposure'],
      ai_summary: 'Lagos subscriber reporting 4 months of unauthorized VAS deductions totalling ₦2,000. Classic CRBT subscription fraud pattern.',
      ai_reply: "Hi Yetunde, we've identified the unauthorized subscription and cancelled it immediately. A full ₦2,000 reversal is being processed right now. We're also flagging this for our VAS compliance team. ^ORCA",
      suggested_offer: 'Full ₦2,000 refund + VAS lock on account + apology airtime',
    },
    escalation: null,
  },
  {
    id: 15,
    tweet_id: '1780001000015',
    text: "@MTNNigeria your 5G coverage map shows my area as covered but I'm getting 3G at best. Paid extra for 5G capable SIM too. Where is the 5G? Very misleading advertising.",
    posted_at: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
    likes: 43, retweets: 28, replies: 16,
    url: 'https://twitter.com/ugo_vi',
    customer: {
      id: 115, handle: 'ugo_vi', display_name: 'Ugochukwu Vitalis',
      msisdn: '08022334466', region: 'Lagos', tenure_months: 22,
      arpu_naira: 21000, verified: false, followers: 3400,
    },
    classification: {
      category: 'Network / Connectivity', urgency: 6, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.88,
      churn_risk: 0.64, risk_level: 'HIGH',
      risk_factors: ['False advertising claim', 'Coverage map discrepancy', 'Potential regulatory issue'],
      ai_summary: 'Lagos subscriber claiming 5G coverage map is misleading — receiving 3G only in supposedly 5G-covered area.',
      ai_reply: "Hi Ugochukwu, we're sorry for the discrepancy. 5G rollout is phased and coverage can vary within an area. An agent will contact you with the accurate coverage map and alternative options. ^ORCA",
      suggested_offer: 'Coverage investigation + 3G/4G compensation data bundle',
    },
    escalation: null,
  },
  // --- MEDIUM — agent ping ---
  {
    id: 16,
    tweet_id: '1780001000016',
    text: "@MTNNigeria data balance keeps dropping even when I'm not using my phone. Lost 2GB overnight. Background apps are all restricted. Something is wrong on your end.",
    posted_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    likes: 6, retweets: 2, replies: 1,
    url: 'https://twitter.com/amaka_benin/status/1780001000016',
    customer: {
      id: 116, handle: 'amaka_benin', display_name: 'Amaka Ihejirika',
      msisdn: '08033556677', region: 'Benin City', tenure_months: 27,
      arpu_naira: 8400, verified: false, followers: 310,
    },
    classification: {
      category: 'Data Depletion', urgency: 5, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.87,
      churn_risk: 0.48, risk_level: 'MEDIUM',
      risk_factors: ['Overnight data drain pattern', 'System-side issue suspected'],
      ai_summary: 'Benin City subscriber reporting overnight data drain despite restricted background apps. System-side investigation warranted.',
      ai_reply: "Hi Amaka, we've noted this issue and will review your data usage logs. Please DM us your number so we can investigate and restore any incorrectly deducted data. ^ORCA",
      suggested_offer: '1GB data restoration pending investigation',
    },
    escalation: null,
  },
  {
    id: 17,
    tweet_id: '1780001000017',
    text: "@MTNNigeria been trying to activate the ₦1,500 weekly plan since morning. USSD keeps returning 'transaction failed'. Please help.",
    posted_at: new Date(Date.now() - 13 * 60 * 60 * 1000).toISOString(),
    likes: 1, retweets: 0, replies: 0,
    url: 'https://twitter.com/kelvin_delta/status/1780001000017',
    customer: {
      id: 117, handle: 'kelvin_delta', display_name: 'Kelvin Okonkwo',
      msisdn: '08044557788', region: 'Asaba', tenure_months: 14,
      arpu_naira: 5800, verified: false, followers: 180,
    },
    classification: {
      category: 'Service Activation', urgency: 5, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.85,
      churn_risk: 0.42, risk_level: 'MEDIUM',
      risk_factors: ['USSD activation failure', 'Day-long issue'],
      ai_summary: 'Asaba subscriber unable to activate weekly data plan via USSD all day. Platform-side activation issue.',
      ai_reply: "Hi Kelvin, we're sorry for the activation trouble. Our team will manually activate the ₦1,500 weekly plan on your account right now. You should receive an SMS confirmation shortly. ^ORCA",
      suggested_offer: 'Manual activation + 200MB bonus',
    },
    escalation: null,
  },
  {
    id: 18,
    tweet_id: '1780001000018',
    text: "@MTNNigeria calls keep dropping in Maiduguri central market. Happens every day between 12pm and 3pm. Very bad for business. Please fix.",
    posted_at: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    likes: 9, retweets: 4, replies: 2,
    url: 'https://twitter.com/mallam_borno/status/1780001000018',
    customer: {
      id: 118, handle: 'mallam_borno', display_name: 'Mallam Ibrahim',
      msisdn: '08055668899', region: 'Maiduguri', tenure_months: 58,
      arpu_naira: 6900, verified: false, followers: 220,
    },
    classification: {
      category: 'Network / Connectivity', urgency: 5, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.88,
      churn_risk: 0.44, risk_level: 'MEDIUM',
      risk_factors: ['Recurring peak-hour congestion', 'Market area density issue'],
      ai_summary: 'Maiduguri subscriber reporting consistent peak-hour call drops in central market area. Congestion pattern confirmed.',
      ai_reply: "Hi, we've logged this congestion issue in the Maiduguri central market area and will escalate to our NOC team for capacity review. Thank you for the detailed report. ^ORCA",
      suggested_offer: 'NOC escalation + follow-up SMS once resolved',
    },
    escalation: null,
  },
  {
    id: 19,
    tweet_id: '1780001000019',
    text: "@MTNNigeria received an SMS saying my account will be restricted for 'suspicious activity'. I haven't done anything suspicious. What is this about? Very alarming.",
    posted_at: new Date(Date.now() - 15 * 60 * 60 * 1000).toISOString(),
    likes: 3, retweets: 1, replies: 1,
    url: 'https://twitter.com/patience_anambra/status/1780001000019',
    customer: {
      id: 119, handle: 'patience_anambra', display_name: 'Patience Okeke',
      msisdn: '08066779900', region: 'Awka', tenure_months: 31,
      arpu_naira: 7200, verified: false, followers: 270,
    },
    classification: {
      category: 'SIM & Account Issues', urgency: 6, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.87,
      churn_risk: 0.52, risk_level: 'MEDIUM',
      risk_factors: ['Account restriction warning', 'Customer anxiety', 'Possible false positive'],
      ai_summary: 'Awka subscriber alarmed by account restriction SMS. Likely a false-positive fraud alert. Needs reassurance and account review.',
      ai_reply: "Hi Patience, we're sorry for the alarm. This is sometimes triggered by routine security checks. An agent will review your account within 1 hour and confirm everything is fine. ^ORCA",
      suggested_offer: 'Account review + confirmation call within 1 hour',
    },
    escalation: null,
  },
  {
    id: 20,
    tweet_id: '1780001000020',
    text: "@MTNNigeria why is my phone showing 'No Service' when I travel to Kaduna from Abuja? The highway coverage is terrible. Very frustrating for road travelers.",
    posted_at: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    likes: 14, retweets: 7, replies: 4,
    url: 'https://twitter.com/abubakar_kaduna/status/1780001000020',
    customer: {
      id: 120, handle: 'abubakar_kaduna', display_name: 'Abubakar Sadiq',
      msisdn: '08077889922', region: 'Kaduna', tenure_months: 43,
      arpu_naira: 9100, verified: false, followers: 480,
    },
    classification: {
      category: 'Network / Connectivity', urgency: 5, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.86,
      churn_risk: 0.46, risk_level: 'MEDIUM',
      risk_factors: ['Highway coverage gap', 'Roaming issue', 'Safety concern for travelers'],
      ai_summary: 'Kaduna subscriber reporting coverage dead zones on Abuja-Kaduna highway. Infrastructure gap issue.',
      ai_reply: "Hi Abubakar, thank you for reporting this. The Abuja-Kaduna highway has known coverage gaps that are part of our expansion plan. We'll share your report with our network planning team. ^ORCA",
      suggested_offer: 'Coverage feedback logged + 500MB data bonus',
    },
    escalation: null,
  },
  {
    id: 21,
    tweet_id: '1780001000021',
    text: "@MTNNigeria just recharged ₦5,000 airtime but it hasn't reflected on my account after 20 minutes. Transaction reference: MTN2024050612345. Please investigate.",
    posted_at: new Date(Date.now() - 17 * 60 * 60 * 1000).toISOString(),
    likes: 2, retweets: 0, replies: 1,
    url: 'https://twitter.com/grace_warri/status/1780001000021',
    customer: {
      id: 121, handle: 'grace_warri', display_name: 'Grace Ejiro',
      msisdn: '08088001133', region: 'Warri', tenure_months: 19,
      arpu_naira: 8800, verified: false, followers: 150,
    },
    classification: {
      category: 'Recharge & Vouchers', urgency: 6, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.91,
      churn_risk: 0.47, risk_level: 'MEDIUM',
      risk_factors: ['Recharge delay', 'Transaction reference provided', 'Financial concern'],
      ai_summary: 'Warri subscriber reporting delayed ₦5,000 airtime recharge with transaction reference. Likely processing delay.',
      ai_reply: "Hi Grace, we can see your transaction reference MTN2024050612345. The recharge is processing — please allow up to 30 minutes. If it doesn't reflect, DM us and we'll credit immediately. ^ORCA",
      suggested_offer: 'Transaction trace + manual credit if needed',
    },
    escalation: null,
  },
  {
    id: 22,
    tweet_id: '1780001000022',
    text: "@MTNNigeria how do I transfer data to another MTN number? Tried *131# option 5 but it keeps saying invalid. My wife needs data urgently.",
    posted_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    likes: 0, retweets: 0, replies: 0,
    url: 'https://twitter.com/peter_jos/status/1780001000022',
    customer: null,
    classification: {
      category: 'Data Depletion', urgency: 3, pathway: 'AUTO_REPLY',
      sentiment: 'neutral', language: 'en', confidence: 0.84,
      churn_risk: 0.18, risk_level: 'LOW',
      risk_factors: [],
      ai_summary: 'Subscriber asking how to transfer data. USSD menu navigation issue. Handled automatically.',
      ai_reply: "Hi! To share data, dial *131*7# or use the MyMTN app > Share Data. Ensure both numbers are active MTN lines. You can share a minimum of 50MB. ^ORCA",
      suggested_offer: '',
    },
    escalation: null,
  },
  {
    id: 23,
    tweet_id: '1780001000023',
    text: "@MTNNigeria what is the best data plan for heavy YouTube usage? Streaming 4+ hours daily.",
    posted_at: new Date(Date.now() - 19 * 60 * 60 * 1000).toISOString(),
    likes: 1, retweets: 0, replies: 0,
    url: 'https://twitter.com/samuel_benin/status/1780001000023',
    customer: null,
    classification: {
      category: 'General Rant / Feedback', urgency: 1, pathway: 'AUTO_REPLY',
      sentiment: 'neutral', language: 'en', confidence: 0.91,
      churn_risk: 0.07, risk_level: 'LOW',
      risk_factors: [],
      ai_summary: 'Prospective or casual subscriber asking for data plan recommendation for video streaming.',
      ai_reply: "Hi Samuel! For heavy streaming we recommend our 30GB Monthly plan at ₦3,500 or the Unlimited Nite plan if you stream mainly at night (12am–5am). Check all plans at mtn.ng or dial *131#. ^ORCA",
      suggested_offer: '',
    },
    escalation: null,
  },
  {
    id: 24,
    tweet_id: '1780001000024',
    text: "@MTNNigeria kudos to your team! Called customer care, was attended to in under 5 minutes and my issue was fully resolved. Great improvement. Keep it up! #MTNNigeria",
    posted_at: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    likes: 34, retweets: 8, replies: 3,
    url: 'https://twitter.com/blessing_uyo/status/1780001000024',
    customer: {
      id: 124, handle: 'blessing_uyo', display_name: 'Blessing Nwankwo',
      msisdn: '08011334455', region: 'Uyo', tenure_months: 61,
      arpu_naira: 12400, verified: false, followers: 1100,
    },
    classification: {
      category: 'General Rant / Feedback', urgency: 1, pathway: 'AUTO_REPLY',
      sentiment: 'positive', language: 'en', confidence: 0.98,
      churn_risk: 0.04, risk_level: 'LOW',
      risk_factors: [],
      ai_summary: 'Positive experience report. Subscriber praising fast customer care resolution. Good for brand sentiment.',
      ai_reply: "Thank you so much Blessing! We're delighted to hear that. Your feedback motivates us to keep improving! ^ORCA",
      suggested_offer: '',
    },
    escalation: null,
  },
  {
    id: 25,
    tweet_id: '1780001000025',
    text: "@MTNNigeria my data plan auto-renewed but the data allocated is less than what I paid for. I subscribed to 10GB but only got 7GB. Please check.",
    posted_at: new Date(Date.now() - 21 * 60 * 60 * 1000).toISOString(),
    likes: 5, retweets: 2, replies: 1,
    url: 'https://twitter.com/rotimi_ibadan/status/1780001000025',
    customer: {
      id: 125, handle: 'rotimi_ibadan', display_name: 'Rotimi Adesanya',
      msisdn: '08055441122', region: 'Ibadan', tenure_months: 36,
      arpu_naira: 10500, verified: false, followers: 290,
    },
    classification: {
      category: 'Data Depletion', urgency: 6, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.90,
      churn_risk: 0.54, risk_level: 'MEDIUM',
      risk_factors: ['Under-allocation on renewal', 'Billing system discrepancy'],
      ai_summary: 'Ibadan subscriber reporting 3GB shortfall on 10GB plan renewal. System-side provisioning discrepancy.',
      ai_reply: "Hi Rotimi, we've verified your account and can see the shortfall. We're crediting the missing 3GB to your account right now — please check your balance in 10 minutes. ^ORCA",
      suggested_offer: 'Immediate 3GB credit + investigation of provisioning error',
    },
    escalation: null,
  },
  {
    id: 26,
    tweet_id: '1780001000026',
    text: "@MTNNigeria MoMo wallet transfer failed but money was deducted from my account. ₦25,000 gone. Transaction ID: MOM20240506789. This is very urgent please.",
    posted_at: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
    likes: 16, retweets: 9, replies: 5,
    url: 'https://twitter.com/emeka_ogun/status/1780001000026',
    customer: {
      id: 126, handle: 'emeka_ogun', display_name: 'Emeka Igwe',
      msisdn: '08066554433', region: 'Abeokuta', tenure_months: 28,
      arpu_naira: 13200, verified: false, followers: 620,
    },
    classification: {
      category: 'Billing & Charges', urgency: 8, pathway: 'ESCALATE_FLAG',
      sentiment: 'negative', language: 'en', confidence: 0.95,
      churn_risk: 0.76, risk_level: 'HIGH',
      risk_factors: ['Failed transfer + deduction', 'Large amount', 'MoMo platform issue', 'Financial distress'],
      ai_summary: 'Subscriber reporting failed ₦25,000 MoMo transfer with confirmed deduction. Financial urgency, needs immediate reversal.',
      ai_reply: "Hi Emeka, we've found your transaction MOM20240506789 and confirmed the deduction. The reversal has been initiated and will credit within 2 hours. We sincerely apologise. ^ORCA",
      suggested_offer: 'Immediate reversal + ₦2,000 goodwill credit for the stress',
    },
    escalation: {
      id: 1009, status: 'QUEUED', assigned_to: '',
      queued_at: new Date(Date.now() - 21.5 * 60 * 60 * 1000).toISOString(),
      accepted_at: null, resolved_at: null, notes: '', final_reply: '',
    },
  },
  {
    id: 27,
    tweet_id: '1780001000027',
    text: "@MTNNigeria internet keeps buffering during my online classes. I'm a medical student and I keep missing important live lectures. Please this is urgent.",
    posted_at: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
    likes: 28, retweets: 14, replies: 7,
    url: 'https://twitter.com/premed_chioma/status/1780001000027',
    customer: {
      id: 127, handle: 'premed_chioma', display_name: 'Chioma Uzoigwe',
      msisdn: '08077661100', region: 'Enugu', tenure_months: 16,
      arpu_naira: 8700, verified: false, followers: 1800,
    },
    classification: {
      category: 'Network / Connectivity', urgency: 7, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.93,
      churn_risk: 0.57, risk_level: 'MEDIUM',
      risk_factors: ['Education impact', 'Public sympathy angle', 'Young subscriber base'],
      ai_summary: 'Medical student in Enugu reporting buffering during live lectures. Education-impacting network issue with high sympathy potential.',
      ai_reply: "Hi Chioma, we understand how critical reliable internet is for your studies. An agent will contact you shortly to troubleshoot and ensure you have stable connectivity. ^ORCA",
      suggested_offer: 'Network troubleshoot + emergency 2GB education bonus',
    },
    escalation: null,
  },
  {
    id: 28,
    tweet_id: '1780001000028',
    text: "@MTNNigeria NIN-SIM linkage verification keeps failing online. I've tried the portal 10 times. Deadline is approaching. MTN offices are telling me to try online. Going in circles!",
    posted_at: new Date(Date.now() - 24 * 60 * 60 * 1000 + 5 * 60 * 1000).toISOString(),
    likes: 41, retweets: 29, replies: 18,
    url: 'https://twitter.com/dapo_ekiti/status/1780001000028',
    customer: {
      id: 128, handle: 'dapo_ekiti', display_name: 'Dapo Olawale',
      msisdn: '08088771122', region: 'Ekiti', tenure_months: 47,
      arpu_naira: 8200, verified: false, followers: 3200,
    },
    classification: {
      category: 'SIM & Account Issues', urgency: 7, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.92,
      churn_risk: 0.60, risk_level: 'HIGH',
      risk_factors: ['NCC compliance deadline', 'Portal failure', 'Regulatory line suspension risk'],
      ai_summary: 'Ekiti subscriber with recurring NIN-SIM portal failures. Approaching NCC deadline creates regulatory urgency — line suspension risk.',
      ai_reply: "Hi Dapo, we know this is frustrating, especially with the deadline. A specialist agent will complete your NIN linkage manually. Please DM us your NIN and we'll handle it from here. ^ORCA",
      suggested_offer: 'Manual NIN linkage by specialist + priority processing',
    },
    escalation: null,
  },
  {
    id: 29,
    tweet_id: '1780001000029',
    text: "@MTNNigeria got a notification saying I used 80% of my data but my phone usage shows only 2GB out of 10GB consumed. Something doesn't add up. Are you throttling?",
    posted_at: new Date(Date.now() - 25 * 60 * 60 * 1000 + 30 * 60 * 1000).toISOString(),
    likes: 7, retweets: 3, replies: 1,
    url: 'https://twitter.com/zainab_kano/status/1780001000029',
    customer: {
      id: 129, handle: 'zainab_kano', display_name: 'Zainab Abdullahi',
      msisdn: '08099112233', region: 'Kano', tenure_months: 24,
      arpu_naira: 7400, verified: false, followers: 380,
    },
    classification: {
      category: 'Data Depletion', urgency: 5, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.88,
      churn_risk: 0.49, risk_level: 'MEDIUM',
      risk_factors: ['Usage discrepancy', 'Throttling allegation', 'System monitoring mismatch'],
      ai_summary: 'Kano subscriber reporting discrepancy between MTN usage notification (80%) and phone usage log (20%). Possible system reporting error.',
      ai_reply: "Hi Zainab, we can see a discrepancy in our usage reporting system. We're reviewing your account logs right now and will update you within 2 hours with a full breakdown. ^ORCA",
      suggested_offer: 'Usage audit + 1GB credit if discrepancy confirmed',
    },
    escalation: null,
  },
  {
    id: 30,
    tweet_id: '1780001000030',
    text: "@MTNNigeria I called customer care yesterday and was told my account issue would be resolved in 24 hours. Now it's been 36 hours and nothing. No callback. No update. Is this a joke?",
    posted_at: new Date(Date.now() - 26 * 60 * 60 * 1000 + 45 * 60 * 1000).toISOString(),
    likes: 19, retweets: 11, replies: 6,
    url: 'https://twitter.com/nnamdi_enugu/status/1780001000030',
    customer: {
      id: 130, handle: 'nnamdi_enugu', display_name: 'Nnamdi Obi',
      msisdn: '08011998877', region: 'Enugu', tenure_months: 39,
      arpu_naira: 11600, verified: false, followers: 920,
    },
    classification: {
      category: 'Customer Service Complaint', urgency: 7, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.93,
      churn_risk: 0.66, risk_level: 'HIGH',
      risk_factors: ['Broken promise SLA', 'No follow-up by agent', '36h overdue'],
      ai_summary: 'Enugu subscriber escalating due to missed 24h resolution promise. No callback received. Agent follow-up failure.',
      ai_reply: "Hi Nnamdi, we sincerely apologise for missing our commitment. This is not acceptable. A senior agent will call you within 30 minutes with a full resolution. ^ORCA",
      suggested_offer: 'Immediate senior agent callback + ₦2,000 compensation for the delay',
    },
    escalation: null,
  },
  {
    id: 31,
    tweet_id: '1780001000031',
    text: "@MTNNigeria I keep receiving OTP messages I didn't request. Someone is trying to access my MoMo account. Very worried about security.",
    posted_at: new Date(Date.now() - 27 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
    likes: 12, retweets: 6, replies: 3,
    url: 'https://twitter.com/ify_abuja2/status/1780001000031',
    customer: {
      id: 131, handle: 'ify_abuja2', display_name: 'Ifeoma Ani',
      msisdn: '08022557733', region: 'Abuja', tenure_months: 55,
      arpu_naira: 16800, verified: false, followers: 740,
    },
    classification: {
      category: 'Fraud & Security', urgency: 8, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.94,
      churn_risk: 0.63, risk_level: 'HIGH',
      risk_factors: ['Unsolicited OTPs', 'MoMo account targeted', 'Social engineering attempt likely'],
      ai_summary: 'Abuja subscriber receiving unsolicited MoMo OTPs — likely targeted by social engineering attackers. Account security review needed.',
      ai_reply: "Hi Ifeoma, please DO NOT share any OTPs with anyone. We're reviewing your account security right now. Change your MoMo PIN immediately and DM us. ^ORCA",
      suggested_offer: 'Immediate security review + MoMo account lock option + fraud alert',
    },
    escalation: null,
  },
  {
    id: 32,
    tweet_id: '1780001000032',
    text: "@MTNNigeria my roaming data isn't working in Ghana. I activated the international plan before travelling. Wasted a whole day without internet. Very bad.",
    posted_at: new Date(Date.now() - 28 * 60 * 60 * 1000 + 30 * 60 * 1000).toISOString(),
    likes: 8, retweets: 4, replies: 2,
    url: 'https://twitter.com/chibundo_roam/status/1780001000032',
    customer: {
      id: 132, handle: 'chibundo_roam', display_name: 'Chibundo Nwosu',
      msisdn: '08033665544', region: 'Lagos', tenure_months: 41,
      arpu_naira: 22000, verified: false, followers: 890,
    },
    classification: {
      category: 'Service Activation', urgency: 6, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.89,
      churn_risk: 0.53, risk_level: 'MEDIUM',
      risk_factors: ['International roaming failure', 'Pre-paid plan activated', 'Business travel impact'],
      ai_summary: 'Lagos subscriber with pre-activated international plan experiencing roaming failure in Ghana. Lost business day.',
      ai_reply: "Hi Chibundo, sorry for the roaming issue. Please try: Settings > Mobile Data > Reset Network Settings. Also ensure 'Data Roaming' is ON. If still failing, DM us your number and we'll fix it remotely. ^ORCA",
      suggested_offer: 'Remote roaming fix + 500MB international bonus',
    },
    escalation: null,
  },
  {
    id: 33,
    tweet_id: '1780001000033',
    text: "@MTNNigeria your app crashes every time I try to buy data. Been like this for 3 days. Your web portal also doesn't load. How am I supposed to buy data??",
    posted_at: new Date(Date.now() - 29 * 60 * 60 * 1000 + 40 * 60 * 1000).toISOString(),
    likes: 33, retweets: 18, replies: 9,
    url: 'https://twitter.com/tosin_oyo/status/1780001000033',
    customer: {
      id: 133, handle: 'tosin_oyo', display_name: 'Tosin Akintola',
      msisdn: '08044778866', region: 'Ibadan', tenure_months: 30,
      arpu_naira: 9500, verified: false, followers: 1450,
    },
    classification: {
      category: 'Service Activation', urgency: 6, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.90,
      churn_risk: 0.51, risk_level: 'MEDIUM',
      risk_factors: ['3-day app outage', 'Dual platform failure', 'Cannot purchase — revenue impact'],
      ai_summary: 'Ibadan subscriber experiencing 3-day MyMTN app and portal failure preventing data purchase. Platform stability issue.',
      ai_reply: "Hi Tosin, we know our app has had issues — we pushed an update this morning to fix it. Please update the app from your store, or dial *131# to buy data instantly while we resolve the portal. ^ORCA",
      suggested_offer: 'USSD workaround guidance + 200MB courtesy data',
    },
    escalation: null,
  },
  {
    id: 34,
    tweet_id: '1780001000034',
    text: "@MTNNigeria please can you confirm if there's network maintenance in Ikeja today? My data and calls have been intermittent since 8am.",
    posted_at: new Date(Date.now() - 30 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
    likes: 4, retweets: 1, replies: 2,
    url: 'https://twitter.com/lola_ikeja/status/1780001000034',
    customer: {
      id: 134, handle: 'lola_ikeja', display_name: 'Lola Balogun',
      msisdn: '08055223344', region: 'Lagos', tenure_months: 22,
      arpu_naira: 6800, verified: false, followers: 310,
    },
    classification: {
      category: 'Network / Connectivity', urgency: 4, pathway: 'AUTO_REPLY',
      sentiment: 'neutral', language: 'en', confidence: 0.87,
      churn_risk: 0.29, risk_level: 'LOW',
      risk_factors: [],
      ai_summary: 'Subscriber asking about maintenance in Ikeja. Polite inquiry about service disruption. Low risk.',
      ai_reply: "Hi Lola! Yes, we have scheduled maintenance in parts of Ikeja today from 8am-2pm. Services should be fully restored by 2pm. Sorry for the inconvenience! ^ORCA",
      suggested_offer: '',
    },
    escalation: null,
  },
  {
    id: 35,
    tweet_id: '1780001000035',
    text: "@MTNNigeria how much does it cost to call a UK number from Nigeria? Traveling soon and want to stay in touch with family.",
    posted_at: new Date(Date.now() - 31 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
    likes: 0, retweets: 0, replies: 1,
    url: 'https://twitter.com/folake_uk/status/1780001000035',
    customer: null,
    classification: {
      category: 'General Rant / Feedback', urgency: 1, pathway: 'AUTO_REPLY',
      sentiment: 'neutral', language: 'en', confidence: 0.95,
      churn_risk: 0.06, risk_level: 'LOW',
      risk_factors: [],
      ai_summary: 'General inquiry about international calling rates to UK. Auto-handled.',
      ai_reply: "Hi! MTN international calls to UK are ₦200/min or activate our International Bundle (₦3,500) for 60 min to UK/US. Dial *131*4# or visit mtn.ng for all IDD rates. ^ORCA",
      suggested_offer: '',
    },
    escalation: null,
  },
  {
    id: 36,
    tweet_id: '1780001000036',
    text: "@MTNNigeria network speed test on MTN results: Download 0.1Mbps Upload 0.0Mbps. Attached screenshot. This is unacceptable for a 'telecommunications company'. #JunkNetwork",
    posted_at: new Date(Date.now() - 32 * 60 * 60 * 1000 + 50 * 60 * 1000).toISOString(),
    likes: 88, retweets: 61, replies: 33,
    url: 'https://twitter.com/adewale_tech/status/1780001000036',
    customer: {
      id: 136, handle: 'adewale_tech', display_name: 'Adewale Ogundimu',
      msisdn: '08077334455', region: 'Lagos', tenure_months: 16,
      arpu_naira: 17500, verified: false, followers: 12400,
    },
    classification: {
      category: 'Network / Connectivity', urgency: 8, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.97,
      churn_risk: 0.74, risk_level: 'HIGH',
      risk_factors: ['Evidence-backed complaint', 'High engagement', 'Tech influencer', 'Screenshot viral potential'],
      ai_summary: 'Tech-savvy Lagos subscriber with speed test screenshot showing near-zero data speeds. High follower count creates viral risk.',
      ai_reply: "Hi Adewale, we can see you're in an area experiencing congestion today. An engineer will contact you within 2 hours to investigate and ensure your experience is corrected. ^ORCA",
      suggested_offer: 'Direct engineer contact + 2GB data compensation',
    },
    escalation: null,
  },
  {
    id: 37,
    tweet_id: '1780001000037',
    text: "@MTNNigeria I activated TikTok night pack but it only works from 12am-3am, not until 6am as advertised. I feel cheated. Please clarify your terms.",
    posted_at: new Date(Date.now() - 33 * 60 * 60 * 1000 + 25 * 60 * 1000).toISOString(),
    likes: 15, retweets: 7, replies: 4,
    url: 'https://twitter.com/youth_abuja/status/1780001000037',
    customer: {
      id: 137, handle: 'youth_abuja', display_name: 'Usman Bello',
      msisdn: '08088442255', region: 'Abuja', tenure_months: 8,
      arpu_naira: 4500, verified: false, followers: 890,
    },
    classification: {
      category: 'Billing & Charges', urgency: 4, pathway: 'AUTO_REPLY',
      sentiment: 'negative', language: 'en', confidence: 0.85,
      churn_risk: 0.34, risk_level: 'LOW',
      risk_factors: ['Terms misunderstanding', 'Product spec complaint'],
      ai_summary: 'Young subscriber disputing TikTok night pack hours. Advertising terms clarification needed.',
      ai_reply: "Hi Usman! The MTN TikTok Night Pack is valid 12am-5am (not 6am — we updated our terms in March, sorry for any old info you saw). If this wasn't clear in your purchase, DM us for a courtesy refund. ^ORCA",
      suggested_offer: 'Terms clarification + refund if terms were misrepresented',
    },
    escalation: null,
  },
  {
    id: 38,
    tweet_id: '1780001000038',
    text: "@MTNNigeria congratulations on the 5G launch! Used it this morning in Victoria Island — blazing fast speeds. This is how it should always be. 👏",
    posted_at: new Date(Date.now() - 34 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
    likes: 127, retweets: 54, replies: 21,
    url: 'https://twitter.com/vp_island/status/1780001000038',
    customer: {
      id: 138, handle: 'vp_island', display_name: 'Vera Philips',
      msisdn: '08033112244', region: 'Lagos', tenure_months: 78,
      arpu_naira: 35000, verified: true, followers: 19800,
    },
    classification: {
      category: 'General Rant / Feedback', urgency: 1, pathway: 'AUTO_REPLY',
      sentiment: 'positive', language: 'en', confidence: 0.99,
      churn_risk: 0.03, risk_level: 'LOW',
      risk_factors: [],
      ai_summary: 'Verified long-tenured Lagos subscriber praising 5G launch in Victoria Island. High follower count — great brand opportunity.',
      ai_reply: "Thank you so much Vera! We're thrilled you experienced our 5G network in VI. We're rolling it out to more areas soon — stay tuned! ^ORCA",
      suggested_offer: '',
    },
    escalation: null,
  },
  {
    id: 39,
    tweet_id: '1780001000039',
    text: "@MTNNigeria I've had the same phone number for 11 years. Your new T&Cs say you can change numbers with 30 days notice?? That's completely unacceptable. I use this number for everything.",
    posted_at: new Date(Date.now() - 35 * 60 * 60 * 1000 + 40 * 60 * 1000).toISOString(),
    likes: 214, retweets: 156, replies: 87,
    url: 'https://twitter.com/veteran_mtn/status/1780001000039',
    customer: {
      id: 139, handle: 'veteran_mtn', display_name: 'Chukwuemeka Ogbonna',
      msisdn: '08011223366', region: 'Lagos', tenure_months: 132,
      arpu_naira: 28000, verified: false, followers: 8900,
    },
    classification: {
      category: 'General Rant / Feedback', urgency: 7, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.93,
      churn_risk: 0.68, risk_level: 'HIGH',
      risk_factors: ['T&C misinterpretation going viral', '11-year subscriber', 'High engagement post', 'Legal concern raised'],
      ai_summary: 'Very long-tenured Lagos subscriber misinterpreting new T&C clause around number assignment. Viral post (200+ engagements) needs careful PR-aware response.',
      ai_reply: "Hi Chukwuemeka! We want to clarify — MTN does not reassign active subscriber numbers. That clause covers inactive numbers only. Your 11-year number is completely safe. We'll send a DM to explain fully. ^ORCA",
      suggested_offer: 'Personal DM clarification + loyalty recognition',
    },
    escalation: null,
  },
  {
    id: 40,
    tweet_id: '1780001000040',
    text: "@MTNNigeria technical fault on my line — incoming calls play a busy tone to callers even though my phone is on. I've missed important calls all day. Please fix urgently.",
    posted_at: new Date(Date.now() - 36 * 60 * 60 * 1000 + 55 * 60 * 1000).toISOString(),
    likes: 6, retweets: 2, replies: 1,
    url: 'https://twitter.com/olu_abuja/status/1780001000040',
    customer: {
      id: 140, handle: 'olu_abuja', display_name: 'Olumide Adeyemi',
      msisdn: '08099887766', region: 'Abuja', tenure_months: 44,
      arpu_naira: 13400, verified: false, followers: 430,
    },
    classification: {
      category: 'SIM & Account Issues', urgency: 7, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.91,
      churn_risk: 0.58, risk_level: 'MEDIUM',
      risk_factors: ['Busy-tone fault on active line', 'All-day impact', 'HLR/switch fault likely'],
      ai_summary: 'Abuja subscriber with call-forwarding or HLR fault causing busy tone to all callers. Technical provisioning issue.',
      ai_reply: "Hi Olumide, we've found a provisioning flag on your account causing this. We're clearing it now — it should resolve within 15 minutes. Please restart your phone after. ^ORCA",
      suggested_offer: '15-minute provisioning fix + follow-up confirmation SMS',
    },
    escalation: null,
  },
  {
    id: 41,
    tweet_id: '1780001000041',
    text: "@MTNNigeria please help. My elderly mother's MTN line has been blocked for 'inactivity'. She's 76 and rarely uses the phone but we need it for emergencies. How do we reactivate?",
    posted_at: new Date(Date.now() - 37 * 60 * 60 * 1000 + 30 * 60 * 1000).toISOString(),
    likes: 41, retweets: 22, replies: 11,
    url: 'https://twitter.com/son_of_mama/status/1780001000041',
    customer: null,
    classification: {
      category: 'SIM & Account Issues', urgency: 5, pathway: 'AUTO_REPLY',
      sentiment: 'neutral', language: 'en', confidence: 0.88,
      churn_risk: 0.22, risk_level: 'LOW',
      risk_factors: ['Elderly subscriber', 'Emergency use case', 'Public sympathy'],
      ai_summary: 'Son seeking reactivation of elderly mother\'s blocked line. Safety/emergency angle creates public sympathy risk.',
      ai_reply: "Hi! We're sorry about this. To reactivate an inactive line, please visit any MTN service centre with your mother's NIN and valid ID. Alternatively, she can dial 180 and an agent can guide you through the process. ^ORCA",
      suggested_offer: '',
    },
    escalation: null,
  },
  {
    id: 42,
    tweet_id: '1780001000042',
    text: "@MTNNigeria MTN data prices have increased AGAIN. 1GB now costs ₦1,500 when it used to be ₦1,000. In this economy? You are adding to our suffering. Shame on you.",
    posted_at: new Date(Date.now() - 38 * 60 * 60 * 1000 + 20 * 60 * 1000).toISOString(),
    likes: 892, retweets: 614, replies: 328,
    url: 'https://twitter.com/angry_naija/status/1780001000042',
    customer: {
      id: 142, handle: 'angry_naija', display_name: 'Damilola Okoye',
      msisdn: '08055990011', region: 'Lagos', tenure_months: 26,
      arpu_naira: 5400, verified: false, followers: 22100,
    },
    classification: {
      category: 'Billing & Charges', urgency: 6, pathway: 'AGENT_PING',
      sentiment: 'negative', language: 'en', confidence: 0.98,
      churn_risk: 0.62, risk_level: 'HIGH',
      risk_factors: ['Viral pricing complaint — 800+ engagements', '22k followers', 'Economic hardship narrative', 'PR crisis risk'],
      ai_summary: 'Highly viral data pricing complaint (890 likes, 614 RTs) from a 22k-follower account. Economic hardship framing creates significant PR risk.',
      ai_reply: "Hi Damilola, we hear you and understand the economic pressure. Our pricing reflects significant network investment costs. However, we have more affordable options — dial *131# to see bundles from ₦300. ^ORCA",
      suggested_offer: 'Low-cost bundle promotion + sensitivity monitoring',
    },
    escalation: null,
  },
  {
    id: 43,
    tweet_id: '1780001000043',
    text: "@MTNNigeria port out process completed yesterday. Just confirming. Was a customer for 7 years. Terrible last 6 months. Goodbye.",
    posted_at: new Date(Date.now() - 39 * 60 * 60 * 1000 + 45 * 60 * 1000).toISOString(),
    likes: 64, retweets: 31, replies: 14,
    url: 'https://twitter.com/ex_mtn_user/status/1780001000043',
    customer: {
      id: 143, handle: 'ex_mtn_user', display_name: 'Rasheed Bello',
      msisdn: '08066112233', region: 'Kano', tenure_months: 84,
      arpu_naira: 11800, verified: false, followers: 2100,
    },
    classification: {
      category: 'Customer Service Complaint', urgency: 3, pathway: 'AUTO_REPLY',
      sentiment: 'negative', language: 'en', confidence: 0.96,
      churn_risk: 1.0, risk_level: 'CRITICAL',
      risk_factors: ['Churned subscriber', 'Public farewell post', '7-year tenure lost'],
      ai_summary: 'Subscriber has already churned after 7 years. Public departure post. Win-back opportunity and reputation management.',
      ai_reply: "Hi Rasheed, we're genuinely sorry we let you down over the last 6 months. We'd love the chance to win you back — please DM us and we'll make a personal offer. We wish you well. ^ORCA",
      suggested_offer: 'Win-back outreach: 3 months premium at entry pricing',
    },
    escalation: null,
  },
  {
    id: 44,
    tweet_id: '1780001000044',
    text: "@MTNNigeria my internet has been off since the rain started last night. Is there an outage in Ibadan? The whole estate seems affected. @MTNNigeria please respond.",
    posted_at: new Date(Date.now() - 40 * 60 * 60 * 1000 + 10 * 60 * 1000).toISOString(),
    likes: 7, retweets: 3, replies: 2,
    url: 'https://twitter.com/ibadan_resident/status/1780001000044',
    customer: {
      id: 144, handle: 'ibadan_resident', display_name: 'Femi Adegbola',
      msisdn: '08077221133', region: 'Ibadan', tenure_months: 35,
      arpu_naira: 8100, verified: false, followers: 560,
    },
    classification: {
      category: 'Network / Connectivity', urgency: 5, pathway: 'AUTO_REPLY',
      sentiment: 'negative', language: 'en', confidence: 0.87,
      churn_risk: 0.38, risk_level: 'LOW',
      risk_factors: ['Weather-related outage', 'Community-scale issue'],
      ai_summary: 'Ibadan subscriber reporting weather-related internet outage affecting whole estate. Known weather event.',
      ai_reply: "Hi Femi! Yes, last night's storms caused some equipment damage in parts of Ibadan. Our team is restoring services — estimated full recovery by 2pm today. Sorry for the disruption! ^ORCA",
      suggested_offer: '',
    },
    escalation: null,
  },
  {
    id: 45,
    tweet_id: '1780001000045',
    text: "@MTNNigeria I've been trying to reach your customer care for 3 days about a billing error. Call center says call back. Chatbot useless. Twitter seems to be the only way to get attention. This is 2024!",
    posted_at: new Date(Date.now() - 41 * 60 * 60 * 1000 + 35 * 60 * 1000).toISOString(),
    likes: 73, retweets: 48, replies: 27,
    url: 'https://twitter.com/omowunmi_lagos/status/1780001000045',
    customer: {
      id: 145, handle: 'omowunmi_lagos', display_name: 'Omowunmi Adeleke',
      msisdn: '08088667799', region: 'Lagos', tenure_months: 57,
      arpu_naira: 19200, verified: false, followers: 5600,
    },
    classification: {
      category: 'Customer Service Complaint', urgency: 8, pathway: 'ESCALATE_FLAG',
      sentiment: 'negative', language: 'en', confidence: 0.96,
      churn_risk: 0.78, risk_level: 'HIGH',
      risk_factors: ['3-day unresolved issue', 'Multi-channel failure', 'High engagement', 'Social media as last resort'],
      ai_summary: 'Long-tenured Lagos subscriber forced to Twitter after 3 days of call center and chatbot failures. Billing error still unresolved.',
      ai_reply: "Hi Omowunmi, we are so sorry you had to come this far to get help. That is completely unacceptable. Please DM us your account details right now — you'll have a resolution within 2 hours, guaranteed. ^ORCA",
      suggested_offer: 'Priority DM resolution + ₦3,000 compensation for the experience',
    },
    escalation: {
      id: 1010, status: 'QUEUED', assigned_to: '',
      queued_at: new Date(Date.now() - 41 * 60 * 60 * 1000).toISOString(),
      accepted_at: null, resolved_at: null, notes: '', final_reply: '',
    },
  },
];

export const MOCK_MENTION_LIST: MentionList = {
  items: MOCK_MENTIONS,
  total: MOCK_MENTIONS.length,
};

export const MOCK_QUEUE_LIST: QueueList = {
  items: MOCK_MENTIONS
    .filter((m) => m.escalation !== null)
    .map((m) => ({
      escalation_id: m.escalation!.id,
      queued_at: m.escalation!.queued_at,
      status: m.escalation!.status,
      assigned_to: m.escalation!.assigned_to,
      mention: m,
    })),
  total: MOCK_MENTIONS.filter((m) => m.escalation !== null).length,
};

export const MOCK_PRIORITY_ROWS: PriorityRow[] = [
  {
    category: 'Network / Connectivity',
    volume: 187,
    avg_urgency: 8.4,
    sentiment_trend: -0.44,
    resolution_rate: 0.54,
    score: 138.7,
    recommended_action: 'Prioritise Lekki Phase 1 and Wuse II tower maintenance. Increase NOC monitoring to 15-min intervals. Dispatch field engineers to Surulere congestion hotspot.',
    owner_team: 'Network Ops',
  },
  {
    category: 'Data Depletion',
    volume: 218,
    avg_urgency: 7.9,
    sentiment_trend: -0.36,
    resolution_rate: 0.68,
    score: 121.4,
    recommended_action: 'Audit bundle consumption logging pipeline for over-reporting. Deploy proactive data alert SMS at 70% usage. Investigate overnight drain pattern in Benin City cluster.',
    owner_team: 'Network Ops',
  },
  {
    category: 'Billing & Charges',
    volume: 142,
    avg_urgency: 7.8,
    sentiment_trend: -0.41,
    resolution_rate: 0.71,
    score: 98.2,
    recommended_action: 'Run duplicate-charge audit on billing system for T-7 days. Audit VAS CRBT subscriptions for unauthorized sign-ups. Auto-reverse confirmed duplicates within 24h SLA.',
    owner_team: 'Billing & Finance',
  },
  {
    category: 'Customer Service Complaint',
    volume: 118,
    avg_urgency: 7.2,
    sentiment_trend: -0.32,
    resolution_rate: 0.58,
    score: 87.6,
    recommended_action: 'Review IVR hold-time routing logic — current avg 47 min is above 20 min SLA. Implement callback-first protocol for queues over 15 min. Audit agent promise-to-resolution tracking.',
    owner_team: 'CX Operations',
  },
  {
    category: 'Fraud & Security',
    volume: 38,
    avg_urgency: 9.1,
    sentiment_trend: -0.55,
    resolution_rate: 0.61,
    score: 84.3,
    recommended_action: 'Activate 24h SIM swap fraud monitoring alert for accounts showing OTP bursts. Integrate with bank fraud teams (UBA, GTB) for real-time SIM swap notifications.',
    owner_team: 'Security & Fraud',
  },
  {
    category: 'Recharge & Vouchers',
    volume: 89,
    avg_urgency: 6.7,
    sentiment_trend: -0.24,
    resolution_rate: 0.74,
    score: 62.8,
    recommended_action: 'Investigate PIN leakage at retail level in Enugu and Kano zones. Engage retail fraud team for outlet audit. Deploy PIN re-issue API for affected customers.',
    owner_team: 'Retail & Fraud',
  },
  {
    category: 'SIM & Account Issues',
    volume: 54,
    avg_urgency: 6.4,
    sentiment_trend: -0.18,
    resolution_rate: 0.77,
    score: 41.2,
    recommended_action: 'Improve NIN-SIM portal reliability — current 22% failure rate exceeds 5% NCC guideline. Add manual NIN processing fallback for backlog. Train front-line staff on HLR fault detection.',
    owner_team: 'Digital Platforms',
  },
  {
    category: 'Service Activation',
    volume: 39,
    avg_urgency: 6.1,
    sentiment_trend: -0.14,
    resolution_rate: 0.80,
    score: 28.4,
    recommended_action: 'Review auto-renewal engine for SmartConnect plans — 3% failure rate detected. Improve MyMTN app stability (3-day outage unacceptable). Test roaming activation end-to-end for West Africa routes.',
    owner_team: 'Digital Platforms',
  },
];

export const MOCK_HEATMAP: Heatmap = {
  regions: ['Lagos', 'Abuja', 'Port Harcourt', 'Kano', 'Ibadan', 'Enugu', 'Owerri', 'Warri'],
  bands: ['₦0–5k', '₦5–15k', '₦15–30k', '₦30k+'],
  cells: [
    { region: 'Lagos', arpu_band: '₦0–5k', customers: 342, avg_risk: 0.28, critical_count: 8 },
    { region: 'Lagos', arpu_band: '₦5–15k', customers: 198, avg_risk: 0.45, critical_count: 17 },
    { region: 'Lagos', arpu_band: '₦15–30k', customers: 121, avg_risk: 0.64, critical_count: 28 },
    { region: 'Lagos', arpu_band: '₦30k+', customers: 64, avg_risk: 0.83, critical_count: 19 },
    { region: 'Abuja', arpu_band: '₦0–5k', customers: 188, avg_risk: 0.31, critical_count: 5 },
    { region: 'Abuja', arpu_band: '₦5–15k', customers: 152, avg_risk: 0.51, critical_count: 14 },
    { region: 'Abuja', arpu_band: '₦15–30k', customers: 94, avg_risk: 0.73, critical_count: 22 },
    { region: 'Abuja', arpu_band: '₦30k+', customers: 39, avg_risk: 0.89, critical_count: 16 },
    { region: 'Port Harcourt', arpu_band: '₦0–5k', customers: 143, avg_risk: 0.34, critical_count: 6 },
    { region: 'Port Harcourt', arpu_band: '₦5–15k', customers: 111, avg_risk: 0.53, critical_count: 12 },
    { region: 'Port Harcourt', arpu_band: '₦15–30k', customers: 73, avg_risk: 0.69, critical_count: 18 },
    { region: 'Port Harcourt', arpu_band: '₦30k+', customers: 28, avg_risk: 0.81, critical_count: 9 },
    { region: 'Kano', arpu_band: '₦0–5k', customers: 259, avg_risk: 0.22, critical_count: 4 },
    { region: 'Kano', arpu_band: '₦5–15k', customers: 184, avg_risk: 0.37, critical_count: 7 },
    { region: 'Kano', arpu_band: '₦15–30k', customers: 69, avg_risk: 0.54, critical_count: 9 },
    { region: 'Kano', arpu_band: '₦30k+', customers: 22, avg_risk: 0.61, critical_count: 4 },
    { region: 'Ibadan', arpu_band: '₦0–5k', customers: 194, avg_risk: 0.26, critical_count: 4 },
    { region: 'Ibadan', arpu_band: '₦5–15k', customers: 147, avg_risk: 0.42, critical_count: 9 },
    { region: 'Ibadan', arpu_band: '₦15–30k', customers: 88, avg_risk: 0.57, critical_count: 13 },
    { region: 'Ibadan', arpu_band: '₦30k+', customers: 31, avg_risk: 0.76, critical_count: 8 },
    { region: 'Enugu', arpu_band: '₦0–5k', customers: 121, avg_risk: 0.30, critical_count: 3 },
    { region: 'Enugu', arpu_band: '₦5–15k', customers: 95, avg_risk: 0.48, critical_count: 8 },
    { region: 'Enugu', arpu_band: '₦15–30k', customers: 57, avg_risk: 0.66, critical_count: 14 },
    { region: 'Enugu', arpu_band: '₦30k+', customers: 18, avg_risk: 0.79, critical_count: 6 },
    { region: 'Owerri', arpu_band: '₦0–5k', customers: 88, avg_risk: 0.27, critical_count: 2 },
    { region: 'Owerri', arpu_band: '₦5–15k', customers: 71, avg_risk: 0.43, critical_count: 6 },
    { region: 'Owerri', arpu_band: '₦15–30k', customers: 44, avg_risk: 0.61, critical_count: 10 },
    { region: 'Owerri', arpu_band: '₦30k+', customers: 14, avg_risk: 0.74, critical_count: 4 },
    { region: 'Warri', arpu_band: '₦0–5k', customers: 74, avg_risk: 0.29, critical_count: 2 },
    { region: 'Warri', arpu_band: '₦5–15k', customers: 58, avg_risk: 0.44, critical_count: 5 },
    { region: 'Warri', arpu_band: '₦15–30k', customers: 36, avg_risk: 0.62, critical_count: 8 },
    { region: 'Warri', arpu_band: '₦30k+', customers: 11, avg_risk: 0.77, critical_count: 3 },
  ],
};

export const MOCK_MENTION_DETAIL = {
  ...MOCK_MENTIONS[0],
  customer_history: [
    {
      id: 998,
      text: '@MTNNigeria data finished again, this is the second time this month!',
      posted_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
      category: 'Data Depletion',
      risk_level: 'HIGH' as const,
    },
    {
      id: 912,
      text: '@MTNNigeria why was I charged ₦500 for a service I never subscribed to? Please reverse.',
      posted_at: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
      category: 'Billing & Charges',
      risk_level: 'MEDIUM' as const,
    },
    {
      id: 887,
      text: '@MTNNigeria network keep dropping in Wuse 2, very annoying',
      posted_at: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000).toISOString(),
      category: 'Network / Connectivity',
      risk_level: 'MEDIUM' as const,
    },
    {
      id: 801,
      text: '@MTNNigeria it took 3 calls to sort out my SIM swap. Customer care needs to improve.',
      posted_at: new Date(Date.now() - 67 * 24 * 60 * 60 * 1000).toISOString(),
      category: 'Customer Service Complaint',
      risk_level: 'LOW' as const,
    },
  ],
};
